-- =====================================================
-- 06_views.sql (DEPRECATED)
-- Las vistas legacy se reemplazaron por v_control_unificado.
-- Mantener este archivo como no-op para instalaciones nuevas.
-- =====================================================
